workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.faustine.soleilterrasse
      xcode: latest
    scripts:
      - name: Build ipa
        script: |
          xcode-project use-profiles
          xcode-project build-ipa \
            --project "Soleil En Terrasse.xcodeproj" \
            --scheme "Soleil En Terrasse"
    artifacts:
      - build/ios/ipa/*.ipa
