workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic
    environment:
      groups:
        - DEFAULT
      xcode: latest
    scripts:
      - name: Set up signing
        script: |
          keychain initialize
          keychain add-certificates --certificate $CM_CERTIFICATE --certificate-password $CM_CERTIFICATE_PASSWORD
          app-store-connect fetch-signing-files \
            com.faustine.soleilterrasse \
            --type IOS_APP_STORE \
            --create
          xcode-project use-profiles
      - name: Build ipa
        script: |
          xcodebuild \
            -project "Soleil En Terrasse.xcodeproj" \
            -scheme "Soleil En Terrasse" \
            -configuration Release \
            -archivePath build/Soleil.xcarchive \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="SoleilAppStore" \
            DEVELOPMENT_TEAM=74UG5W2ZY8 \
            archive
    artifacts:
      - build/Soleil.xcarchive
